# Generated by Django 5.1 on 2024-10-29 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_medico_apellido_remove_medico_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipomedico'),
        ),
    ]
